# Generated by Django 2.0.6 on 2018-06-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarShipapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nave',
            name='foto_de_nave',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
    ]
