# Generated by Django 2.0.6 on 2018-06-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StarShipapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='datanascimento',
            field=models.DateField(),
        ),
    ]
